name: Clang Build Analyzer

on:
  push:
    branches:
    - master
  workflow_dispatch:

# Mixing in event_name so that a master push and a workflow dispatch can run at the same time.
concurrency: clang_build_analyzer-${{ github.event_name }}

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        persist-credentials: false
    - name: install dependencies
      run: sudo apt-get install libncursesw5-dev gettext
    - name: Prepare Build Analyzer
      run: |
        cd
        git clone --recursive https://github.com/aras-p/ClangBuildAnalyzer.git buildAnalyzer
        cd buildAnalyzer
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=RELEASE ..
        cmake --build . -- -j3
        echo "${PWD}" >> $GITHUB_PATH
    - uses: ammaraskar/gcc-problem-matcher@0f9c86f9e693db67dacf53986e1674de5f2e5f28 # master
    - name: make
      run: |
        clang++ --version
        ClangBuildAnalyzer --start .
        CLANG=clang++ CXXFLAGS=-ftime-trace make
        ClangBuildAnalyzer --stop . buildAnalysis
    - name: Analyze
      run: ClangBuildAnalyzer --analyze buildAnalysis
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: ClangBuildAnalyzer-analysis
        path: buildAnalysis
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: ClangBuildAnalyzer-traces
        path: "**/obj/*.json"
