name: "Push translation template"

concurrency: push_transifex

on:
  push:
    branches:
      - master
    paths:
      - '**.json'
      - 'src/**.cpp'
      - 'src/**.h'
      - 'lang/extract_json_strings.py'
      - 'lang/strip_line_numbers.py'
      - 'lang/update_pot.sh'
      - 'lang/unicode_check.py'


jobs:
  push-template:
    if: github.repository == CleverRaven
    runs-on: ubuntu-20.04
    steps:
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install gettext python3-pip
          sudo pip3 install transifex-client
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Generate translation template"
        run: |
          lang/update_pot.sh
      - name: "Push translation template to Transifex server"
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 5
          retry_on: error
          command: |
            export TX_TOKEN=$TOKEN
            tx push --source --no-interactive --resource cataclysm-dda.master-cataclysm-dda
            unset TX_TOKEN
            unset TOKEN
      - name: Sleep for 5 minutes
        run: sleep 5m
        shell: bash
